spring.application.name=SpringSecEx

spring.security.user.name=biswaraj
spring.security.user.password=toor

spring.datasource.url=jdbc:postgresql://localhost:5432/biswaraj_db
spring.datasource.username=postgres
spring.datasource.password=Biswaraj